In [11]:
#Step1

import pandas as pd

# Define a dictionary containing employee data
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32]}

In [12]:
# Define a dictionary containing employee data
data2 = {'key': ['K1', 'K2', 'K3', 'K4'],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

In [16]:
# Convert the dictionary into DataFrame
df = pd.DataFrame(data1)
df

key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

In [17]:
df1 = pd.DataFrame(data2)
df1

key    Address Qualification
0  K1     Nagpur         Btech
1  K2     Kanpur           B.A
2  K3  Allahabad          Bcom
3  K4    Kannuaj        B.hons

In [18]:
#step2

import pandas as pd
data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata',
              'Mahindra', 'Maruti', 'Hyundai',
              'Renault', 'Tata', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2012,
             2016, 2014, 2018, 2019],
    'Kms Driven': [50000, 30000, 60000,
                   25000, 10000, 46000,
                   31000, 15000, 12000],
    'City': ['Gurgaon', 'Delhi', 'Mumbai',
             'Delhi', 'Mumbai', 'Delhi',
             'Mumbai', 'Chennai', 'Ghaziabad'],
    'Mileage': [28, 27, 25, 26, 28,
                29, 24, 21, 24]
})
display(data)

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [19]:
filtered_data = data[(data['Brand'] == 'Tata') & (data['Year'] == 2011)]
display(filtered_data)

Brand  Year  Kms Driven    City  Mileage
2  Tata  2011       60000  Mumbai       25

In [20]:
fd=data[(data.Brand == 'Maruti') & (data.Year == 2012)]
display(fd)

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [21]:
display(data.loc[(data.Brand == 'Maruti') & (data.Year == 2012)])

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [22]:
display(data.loc[(data.Brand == 'Hyundai') & (data.Year == 2014)])

Brand  Year  Kms Driven   City  Mileage
1  Hyundai  2014       30000  Delhi       27

In [23]:
display(data['Kms Driven'].mean())

31000.0

In [24]:
display(data['Year'].mean())

2014.5555555555557

In [25]:
display(data['Mileage'].mean())

25.77777777777778

In [29]:
display(data['Year'])

0    2012
1    2014
2    2011
3    2015
4    2012
5    2016
6    2014
7    2018
8    2019
Name: Year, dtype: int64

In [33]:
print(data.columns)

Index(['Brand', 'Year', 'Kms Driven', 'City', 'Mileage'], dtype='object')


In [35]:
Year = 'Year'
display(data[Year].sum() / len(data[Year]))

2014.5555555555557

In [36]:
#step3

In [43]:
import numpy as np
array = np.arange(20).reshape(2,10)
#arrange the array of 50 numbers with different column shapes
ar = np.arange(50).reshape(5,10)
arr = np.arange(50).reshape(10,5)
arr1 = np.arange(50).reshape(2,25)
arr2 = np.arange(50).reshape(25,2)
print(arr1)
print()
print(arr2)
print()
print(array)
print()
print(ar)
print()
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
